version: "3"

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  chatapp1:
    image: chatapp
    environment:
      - APPID=1111
  chatapp2:
    image: chatapp
    environment:
      - APPID=2222
  chatapp3:
    image: chatapp
    environment:
      - APPID=3333
  chatapp4:
    image: chatapp
    environment:
      - APPID=4444
  rds:
    image: redis 
